import type { Dataset } from "../types";

/** Generated by scripts/build-amazon-csv.mjs, served from public/. */
export const AMAZON_DATASET_FILE = "amazon-products.csv";
export const AMAZON_DATASET_LABEL = "Amazon product records";

/**
 * What one row of a dataset actually is, so the UI can name it truthfully.
 *
 * The Amazon dataset's rows are product listings — each carries a product-average
 * rating and several customers' reviews concatenated into one cell — so calling
 * them "reviews" would overstate what the numbers mean. Sample and uploaded data
 * are genuine per-customer reviews and keep that word.
 */
export interface DatasetUnit {
  one: string;
  many: string;
  /** True when a row is a product record rather than a single customer review. */
  isProductLevel: boolean;
}

const PRODUCT_RECORD: DatasetUnit = {
  one: "product record",
  many: "product records",
  isProductLevel: true,
};
const REVIEW: DatasetUnit = { one: "review", many: "reviews", isProductLevel: false };

export function unitFor(dataset: Dataset): DatasetUnit {
  return dataset.source === "amazon" ? PRODUCT_RECORD : REVIEW;
}

/** `count` with the dataset's unit noun, e.g. "1,464 product records". */
export function formatCount(count: number, unit: DatasetUnit): string {
  return `${count.toLocaleString()} ${count === 1 ? unit.one : unit.many}`;
}

/**
 * Whether a dataset carries per-review dates. False when any review is undated
 * (`date: ""`), which is the safe direction: the empty window an undated dataset
 * uses matches undated reviews only, so a mixed dataset must never be treated as
 * dated or its dated rows would be silently excluded.
 */
export function hasDates(dataset: Dataset): boolean {
  return dataset.reviews.length > 0 && dataset.reviews.every((r) => r.date !== "");
}
