import type { Dataset } from "../types";
import { formatDate } from "./date";

/** Generated by scripts/build-amazon-csv.mjs, served from public/. Not committed. */
export const AMAZON_DATASET_FILE = "amazon-products.csv";
export const AMAZON_DATASET_LABEL = "Amazon product records";

/**
 * Committed, fully synthetic stand-in in the generated fixture's column shape.
 * Deployed builds have no real dataset (it is not redistributed), so they fall
 * back to this — the Amazon adapter, undated behaviour and product-record
 * wording all stay exercised, on invented data that is labelled as invented.
 */
export const AMAZON_DEMO_FILE = "amazon-demo.csv";
export const AMAZON_DEMO_LABEL = "Amazon demo records (synthetic)";

/** The bundled 204-review demo CSV, also served from public/. */
export const SAMPLE_CSV_FILE = "sample-reviews.csv";

/**
 * What one row of a dataset actually is, so the UI can name it truthfully.
 *
 * The Amazon dataset's rows are product listings — each carries a product-average
 * rating and several customers' reviews concatenated into one cell — so calling
 * them "reviews" would overstate what the numbers mean. Sample and uploaded data
 * are genuine per-customer reviews and keep that word.
 */
export interface DatasetUnit {
  one: string;
  many: string;
  /** True when a row is a product record rather than a single customer review. */
  isProductLevel: boolean;
}

export const PRODUCT_RECORD: DatasetUnit = {
  one: "product record",
  many: "product records",
  isProductLevel: true,
};
export const REVIEW: DatasetUnit = { one: "review", many: "reviews", isProductLevel: false };

export function unitFor(dataset: Dataset): DatasetUnit {
  return dataset.source === "amazon" ? PRODUCT_RECORD : REVIEW;
}

/**
 * Whether the active Amazon data is the synthetic stand-in rather than the real
 * dataset. The UI says so wherever it matters — a visitor must never mistake
 * invented records for real customer feedback.
 */
export function isSyntheticDemo(dataset: Dataset): boolean {
  return dataset.source === "amazon" && dataset.label === AMAZON_DEMO_LABEL;
}

/** The unit noun agreeing with `count`, e.g. "product record" / "product records". */
export function pluralize(count: number, unit: DatasetUnit): string {
  return count === 1 ? unit.one : unit.many;
}

/** `count` with the dataset's unit noun, e.g. "1,464 product records". */
export function formatCount(count: number, unit: DatasetUnit): string {
  return `${count.toLocaleString()} ${pluralize(count, unit)}`;
}

/**
 * What an analysis covered, for sentences like "no themes have enough evidence
 * …". Dated data is bounded by the window the analyst chose; undated data is
 * bounded only by the rows themselves, so saying "window" there would describe
 * a control the UI does not show.
 */
export function scopeLabel(unit: DatasetUnit, hasReviewDates: boolean): string {
  return hasReviewDates ? "in this window" : `in these ${unit.many}`;
}

/**
 * The trailing " · from – to" of a stats line, or "" when the data has no
 * dates — an undated dataset gets no date range rather than an empty one.
 */
export function dateRangeSuffix(from: string, to: string, hasReviewDates: boolean): string {
  return hasReviewDates ? ` · ${formatDate(from)} – ${formatDate(to)}` : "";
}

/**
 * Whether a dataset carries per-review dates. False when any review is undated
 * (`date: ""`), which is the safe direction: the empty window an undated dataset
 * uses matches undated reviews only, so a mixed dataset must never be treated as
 * dated or its dated rows would be silently excluded.
 */
export function hasDates(dataset: Dataset): boolean {
  return dataset.reviews.length > 0 && dataset.reviews.every((r) => r.date !== "");
}
