import type { AnalysisResult, Finding, PromotionInsight } from "../types";
import { formatDate } from "./date";
import type { DatasetUnit } from "./datasetInfo";

/** Default unit: per-customer reviews, which is what sample and uploaded data are. */
const REVIEW_UNIT: DatasetUnit = { one: "review", many: "reviews", isProductLevel: false };

/** Today's date as a formatted label, using the shared date formatter. */
function todayFormatted(): string {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  const iso = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
  return formatDate(iso);
}

/** Author fallback so every quote is attributed. */
function author(finding: Finding): string {
  return finding.quoteAuthor.trim() || "Anonymous";
}

/**
 * One evidence-backed finding block: label, counts, percentage, and quote.
 * The evidence line is always kept. A representative quote is included only the
 * first time it appears in the report — `seenQuotes` tracks quotes already
 * shown so the same quote never repeats across findings (it would read as
 * padding in a short report). Later findings that reuse it keep their evidence
 * but omit the duplicate quote.
 */
function findingBlock(
  finding: Finding,
  reviewCount: number,
  unit: DatasetUnit,
  seenQuotes: Set<string>,
): string {
  const lines = [
    `### ${finding.label}`,
    "",
    `- **Evidence:** ${finding.mentions} of ${reviewCount} selected ${unit.many} (${finding.percent}%)`,
  ];
  const quoteKey = finding.quote.trim();
  if (quoteKey && !seenQuotes.has(quoteKey)) {
    seenQuotes.add(quoteKey);
    lines.push(`- **Representative quote:** "${finding.quote}" — ${author(finding)}`);
  }
  return lines.join("\n");
}

/** A findings section, or a fallback line when nothing met the threshold. */
function findingsSection(
  heading: string,
  findings: Finding[],
  reviewCount: number,
  unit: DatasetUnit,
  emptyFallback: string,
  seenQuotes: Set<string>,
): string {
  const body =
    findings.length === 0
      ? emptyFallback
      : findings.map((f) => findingBlock(f, reviewCount, unit, seenQuotes)).join("\n\n");
  return `## ${heading}\n\n${body}`;
}

/**
 * Render a completed `AnalysisResult` as a Markdown report. Pure and
 * deterministic: it never reruns or reinterprets the analysis, and takes an
 * optional `generatedOn` label so tests do not depend on the current date.
 * When omitted, a sensible formatted current date is used.
 *
 * `unit` names what one analyzed row is. It defaults to per-customer reviews;
 * pass the product-level unit for datasets whose rows are product listings, so
 * the report never reports product records as if they were customers.
 */
export function generateMarkdownReport(
  result: AnalysisResult,
  generatedOn?: string,
  unit: DatasetUnit = REVIEW_UNIT,
): string {
  const generated = generatedOn ?? todayFormatted();
  const dated = Boolean(result.from && result.to);

  const header = [
    `# ReviewIQ Report: ${result.productName}`,
    "",
    ...(dated ? [`**Analysis window:** ${formatDate(result.from)} – ${formatDate(result.to)}  `] : []),
    `**${capitalize(unit.many)} analyzed:** ${result.reviewCount}  `,
    `**Average rating:** ${result.averageRating.toFixed(1)}/5`,
    ...(unit.isProductLevel
      ? [
          "",
          "> Each analyzed row is a product record: a product listing whose text bundles several",
          "> customers' reviews, whose star value is a product-average rounded to a whole star, and",
          "> which carries no review date. Counts and percentages are shares of product records,",
          "> not of customers.",
        ]
      : []),
  ].join("\n");

  const summary = `## Summary\n\n${result.summary}`;

  // Shared across both sections so a quote shown under a strength is not
  // repeated under a later strength or issue. Strengths are built first, so the
  // earliest finding to cite a quote is the one that keeps it.
  const seenQuotes = new Set<string>();

  const strengths = findingsSection(
    "Top Strengths",
    result.praise,
    result.reviewCount,
    unit,
    "No strengths met the evidence threshold in this analysis.",
    seenQuotes,
  );

  const issues = findingsSection(
    "Top Issues",
    result.faults,
    result.reviewCount,
    unit,
    "No issues met the evidence threshold in this analysis.",
    seenQuotes,
  );

  const recommendations =
    result.recommendations.length === 0
      ? "## Recommendations\n\nNo actions were recommended because no recurring issues met the evidence threshold."
      : `## Recommendations\n\n${result.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join("\n")}`;

  const footer = `---\n\n_Generated by ReviewIQ on ${generated}._`;

  // Promotions section is included only when the analysis carries it, so reports
  // over datasets without promotion data keep their existing shape.
  const sections = [header, summary, strengths, issues];
  if (result.promotion) sections.push(promotionsSection(result.promotion));
  sections.push(recommendations, footer);

  return sections.join("\n\n") + "\n";
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/** Markdown for the discounts/promotions insight, preserving its evidence. */
function promotionsSection(insight: PromotionInsight): string {
  const lines = [
    "## Discounts & Promotions",
    "",
    insight.note,
    "",
    `- **Promoted purchases:** ${insight.promoCount} review${insight.promoCount === 1 ? "" : "s"}, ${insight.promoAverageRating.toFixed(1)}/5 average`,
    `- **Full price:** ${insight.fullPriceCount} review${insight.fullPriceCount === 1 ? "" : "s"}, ${insight.fullPriceAverageRating.toFixed(1)}/5 average`,
  ];
  if (insight.promotions.length > 0) {
    lines.push(`- **Promotions seen:** ${insight.promotions.join(", ")}`);
  }
  return lines.join("\n");
}
