import type { AnalysisResult, Finding } from "../types";
import { formatDate } from "./date";

/** Today's date as a formatted label, using the shared date formatter. */
function todayFormatted(): string {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  const iso = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
  return formatDate(iso);
}

/** Author fallback so every quote is attributed. */
function author(finding: Finding): string {
  return finding.quoteAuthor.trim() || "Anonymous";
}

/**
 * One evidence-backed finding block: label, counts, percentage, and quote.
 * The evidence line is always kept. A representative quote is included only the
 * first time it appears in the report — `seenQuotes` tracks quotes already
 * shown so the same quote never repeats across findings (it would read as
 * padding in a short report). Later findings that reuse it keep their evidence
 * but omit the duplicate quote.
 */
function findingBlock(finding: Finding, reviewCount: number, seenQuotes: Set<string>): string {
  const lines = [
    `### ${finding.label}`,
    "",
    `- **Evidence:** ${finding.mentions} of ${reviewCount} selected reviews (${finding.percent}%)`,
  ];
  const quoteKey = finding.quote.trim();
  if (quoteKey && !seenQuotes.has(quoteKey)) {
    seenQuotes.add(quoteKey);
    lines.push(`- **Representative quote:** "${finding.quote}" — ${author(finding)}`);
  }
  return lines.join("\n");
}

/** A findings section, or a fallback line when nothing met the threshold. */
function findingsSection(
  heading: string,
  findings: Finding[],
  reviewCount: number,
  emptyFallback: string,
  seenQuotes: Set<string>,
): string {
  const body =
    findings.length === 0
      ? emptyFallback
      : findings.map((f) => findingBlock(f, reviewCount, seenQuotes)).join("\n\n");
  return `## ${heading}\n\n${body}`;
}

/**
 * Render a completed `AnalysisResult` as a Markdown report. Pure and
 * deterministic: it never reruns or reinterprets the analysis, and takes an
 * optional `generatedOn` label so tests do not depend on the current date.
 * When omitted, a sensible formatted current date is used.
 */
export function generateMarkdownReport(result: AnalysisResult, generatedOn?: string): string {
  const generated = generatedOn ?? todayFormatted();

  const header = [
    `# ReviewIQ Report: ${result.productName}`,
    "",
    `**Analysis window:** ${formatDate(result.from)} – ${formatDate(result.to)}  `,
    `**Reviews analyzed:** ${result.reviewCount}  `,
    `**Average rating:** ${result.averageRating.toFixed(1)}/5`,
  ].join("\n");

  const summary = `## Summary\n\n${result.summary}`;

  // Shared across both sections so a quote shown under a strength is not
  // repeated under a later strength or issue. Strengths are built first, so the
  // earliest finding to cite a quote is the one that keeps it.
  const seenQuotes = new Set<string>();

  const strengths = findingsSection(
    "Top Strengths",
    result.praise,
    result.reviewCount,
    "No strengths met the evidence threshold in this analysis.",
    seenQuotes,
  );

  const issues = findingsSection(
    "Top Issues",
    result.faults,
    result.reviewCount,
    "No issues met the evidence threshold in this analysis.",
    seenQuotes,
  );

  const recommendations =
    result.recommendations.length === 0
      ? "## Recommendations\n\nNo actions were recommended because no recurring issues met the evidence threshold."
      : `## Recommendations\n\n${result.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join("\n")}`;

  const footer = `---\n\n_Generated by ReviewIQ on ${generated}._`;

  return [header, summary, strengths, issues, recommendations, footer].join("\n\n") + "\n";
}
